import "server-only";
import { db, fetchAll } from "@/lib/db";
import { currentUserId } from "@/lib/user";
import { GAME_SERVERS } from "@/features/games/server-registry";
import { sentenceForForm, sentenceForWord, within } from "./ai";
import { clozeAnswerOf, tokenize } from "./text";
import {
  MAX_REVIEW_PER_SESSION,
  NEW_WORDS_PER_SESSION,
  REINFORCEMENT_PER_SESSION,
  fluencyScore,
  interleave,
} from "./leitner";
import {
  FILTER_KINDS,
  type ReviewKind,
  type ReviewStats,
  type Sentence,
  type SessionCard,
  type SessionFilter,
  type WordMode,
} from "./types";
import {
  PRONOUNS,
  TENSE_GROUPS,
  conjRef,
  parseConjRef,
  pickCombos,
  pickDistractors,
  shuffle,
  type Pronoun,
  type Tense,
  type TenseGroup,
  type VerbEntry,
} from "./verbs";

type ItemRow = {
  kind: ReviewKind;
  ref: string;
  source: string;
  box: number;
  next_review_at: string;
  last_reviewed_at: string | null;
};

type WordRow = { id: number; spanish: string; english: string; pos: string | null };

/** Claude gets this long per sentence before a card falls back or is dropped. */
const SENTENCE_TIMEOUT_MS = 12_000;

const KIND_LABEL: Record<ReviewKind, string> = {
  word: "Palabra",
  phrase: "Frase",
  conjugation: "Conjugar",
  game_item: "Juego",
};

// ── queue ────────────────────────────────────────────────────────────────────

async function dueItems(kinds: ReviewKind[], limit: number): Promise<ItemRow[]> {
  const { data, error } = await db()
    .from("srs_items")
    .select("kind, ref, source, box, next_review_at, last_reviewed_at")
    .eq("user_id", currentUserId())
    .eq("suspended", false)
    .in("kind", kinds)
    .lte("next_review_at", new Date().toISOString())
    .order("next_review_at")
    .limit(limit);
  if (error) throw new Error(error.message);
  return (data ?? []) as ItemRow[];
}

async function seenWordIds(): Promise<Set<number>> {
  const rows = await fetchAll<{ ref: string }>((from, to) =>
    db()
      .from("srs_items")
      .select("ref")
      .eq("user_id", currentUserId())
      .eq("kind", "word")
      .order("ref")
      .range(from, to),
  );
  return new Set(rows.map((row) => Number(row.ref.slice(5))));
}

async function newWords(count: number): Promise<WordRow[]> {
  if (count <= 0) return [];
  const seen = await seenWordIds();
  // The list is ~1000 words, so filtering here keeps the query simple.
  const words = await fetchAll<WordRow>((from, to) =>
    db().from("words").select("id, spanish, english, pos").order("rank").range(from, to),
  );
  return words.filter((word) => !seen.has(word.id)).slice(0, count);
}

async function reinforcementItems(exclude: Set<string>): Promise<ItemRow[]> {
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { data, error } = await db()
    .from("srs_items")
    .select("kind, ref, source, box, next_review_at, last_reviewed_at")
    .eq("user_id", currentUserId())
    .eq("kind", "word")
    .eq("suspended", false)
    .in("box", [1, 2])
    .gte("last_reviewed_at", since)
    .order("last_reviewed_at", { ascending: false })
    .limit(REINFORCEMENT_PER_SESSION + exclude.size);
  if (error) throw new Error(error.message);
  return ((data ?? []) as ItemRow[])
    .filter((item) => !exclude.has(item.ref))
    .slice(0, REINFORCEMENT_PER_SESSION);
}

// ── words ────────────────────────────────────────────────────────────────────

async function wordsById(ids: number[]): Promise<Map<number, WordRow>> {
  if (ids.length === 0) return new Map();
  const { data, error } = await db()
    .from("words")
    .select("id, spanish, english, pos")
    .in("id", ids);
  if (error) throw new Error(error.message);
  return new Map(((data ?? []) as WordRow[]).map((word) => [word.id, word]));
}

/**
 * One sentence per word: a cached one when there is any (picked at random so
 * repeats vary), otherwise generated by Claude and cached. Words Claude can't
 * serve in time are left out of the session rather than blocking it.
 */
async function sentencesFor(words: WordRow[]): Promise<Map<number, Sentence>> {
  const out = new Map<number, Sentence>();
  if (words.length === 0) return out;

  const { data, error } = await db()
    .from("word_sentences")
    .select("word_id, spanish, english, cloze")
    .in(
      "word_id",
      words.map((word) => word.id),
    );
  if (error) throw new Error(error.message);

  const cached = new Map<number, Sentence[]>();
  for (const row of data ?? []) {
    const list = cached.get(row.word_id as number) ?? [];
    list.push({ spanish: row.spanish, english: row.english, cloze: row.cloze });
    cached.set(row.word_id as number, list);
  }
  for (const [id, list] of cached) out.set(id, shuffle(list)[0]);

  const missing = words.filter((word) => !out.has(word.id));
  if (missing.length && process.env.ANTHROPIC_API_KEY) {
    const generated = await Promise.all(
      missing.map(async (word) => {
        const sentence = await within(
          sentenceForWord(word.spanish, word.english),
          SENTENCE_TIMEOUT_MS,
        );
        return { word, sentence };
      }),
    );
    const rows = generated.filter((g) => g.sentence);
    for (const { word, sentence } of rows) out.set(word.id, sentence!);
    if (rows.length) {
      const { error: insertError } = await db()
        .from("word_sentences")
        .insert(rows.map(({ word, sentence }) => ({ word_id: word.id, ...sentence! })));
      if (insertError) console.error("[srs] caching sentences failed:", insertError.message);
    }
  }
  return out;
}

function wordCard(
  item: { ref: string; source: string; box: number; isNew: boolean },
  word: WordRow,
  sentence: Sentence,
  view: "cloze" | "scramble",
  others: string[],
): SessionCard {
  const base = {
    key: `${item.ref}:${view}`,
    kind: "word" as const,
    ref: item.ref,
    source: item.source,
    box: item.box,
    isNew: item.isNew,
    label: KIND_LABEL.word,
    word: word.spanish,
    meaning: word.english,
    pos: word.pos,
    sentence,
  };
  if (view === "scramble") {
    const order = shuffle(tokenize(sentence.spanish).map((_, index) => index));
    return { ...base, view, order };
  }
  const answer = clozeAnswerOf(sentence) || word.spanish;
  const distractors = shuffle(others.filter((o) => o.toLowerCase() !== answer.toLowerCase())).slice(0, 3);
  return { ...base, view, options: shuffle([answer, ...distractors]) };
}

// ── phrases ──────────────────────────────────────────────────────────────────

async function phraseCards(items: ItemRow[]): Promise<Map<string, SessionCard>> {
  const out = new Map<string, SessionCard>();
  const ids = items.map((item) => item.ref.slice("phrase:".length));
  if (ids.length === 0) return out;
  const { data, error } = await db()
    .from("phrases")
    .select("id, spanish_text, translation_text")
    .in("id", ids);
  if (error) throw new Error(error.message);
  const byId = new Map((data ?? []).map((row) => [row.id as string, row]));
  for (const item of items) {
    const phrase = byId.get(item.ref.slice("phrase:".length));
    if (!phrase) continue;
    // Recognise first; once it's sticking, produce it.
    const esFirst = item.box <= 2;
    out.set(item.ref, {
      key: item.ref,
      kind: "phrase",
      ref: item.ref,
      source: item.source,
      box: item.box,
      isNew: false,
      label: KIND_LABEL.phrase,
      view: "recall",
      frontLang: esFirst ? "es" : "en",
      front: esFirst ? phrase.spanish_text : phrase.translation_text,
      back: esFirst ? phrase.translation_text : phrase.spanish_text,
    });
  }
  return out;
}

// ── conjugation ──────────────────────────────────────────────────────────────

async function conjugationCard(
  combo: { verb: VerbEntry; tense: Tense; pronoun: Pronoun },
  item: { source: string; box: number; isNew: boolean },
  withSentence: boolean,
): Promise<SessionCard> {
  const { verb, tense, pronoun } = combo;
  const correct = verb.forms[tense][pronoun];
  const sentence = withSentence && process.env.ANTHROPIC_API_KEY
    ? await within(
        sentenceForForm({ infinitive: verb.infinitive, form: correct, pronoun, tense }),
        SENTENCE_TIMEOUT_MS,
      )
    : null;

  const ref = conjRef(verb.infinitive, tense, pronoun);
  return {
    key: ref,
    kind: "conjugation",
    ref,
    source: item.source,
    box: item.box,
    isNew: item.isNew,
    label: `${KIND_LABEL.conjugation} · ${tense}`,
    view: "choice",
    card: {
      type: "choice",
      prompt: sentence
        ? sentence.cloze.replace("{{word}}", "___")
        : `${pronoun} ___ (${verb.infinitive})`,
      hint: sentence
        ? `${sentence.english} — ${verb.infinitive}, ${pronoun}`
        : `${verb.infinitive} — ${verb.english}`,
      options: shuffle([
        { text: correct, correct: true },
        ...pickDistractors(verb, tense, pronoun).map((text) => ({ text, correct: false })),
      ]),
    },
    table: {
      title: `${verb.infinitive} · ${tense}`,
      rows: PRONOUNS.map((p) => [p, verb.forms[tense][p]] as [string, string]),
    },
  };
}

// ── games ────────────────────────────────────────────────────────────────────

async function gameCards(items: ItemRow[]): Promise<Map<string, SessionCard>> {
  const out = new Map<string, SessionCard>();
  const bySlug = new Map<string, ItemRow[]>();
  for (const item of items) {
    const [, slug] = item.ref.split(":");
    bySlug.set(slug, [...(bySlug.get(slug) ?? []), item]);
  }
  await Promise.all(
    [...bySlug].map(async ([slug, slugItems]) => {
      const server = GAME_SERVERS[slug];
      if (!server) return;
      const { content } = await server.loadContent();
      for (const item of slugItems) {
        const itemRef = item.ref.slice(`game:${slug}:`.length);
        const card = server.toReviewCard(itemRef, content);
        if (!card) continue;
        out.set(item.ref, {
          key: item.ref,
          kind: "game_item",
          ref: item.ref,
          source: item.source,
          box: item.box,
          isNew: false,
          label: `${KIND_LABEL.game_item} · ${slug}`,
          view: "choice",
          card: { ...card, options: shuffle(card.options) },
        });
      }
    }),
  );
  return out;
}

// ── session ──────────────────────────────────────────────────────────────────

/**
 * A review session: everything due in the chosen slice (oldest first), then new
 * words, with recently missed words mixed back in. Conjugation "new" cards come
 * from the Conjugar drill, not from here.
 */
export async function buildSession(options: {
  filter: SessionFilter;
  mode: WordMode;
  limit?: number;
}): Promise<SessionCard[]> {
  const kinds = FILTER_KINDS[options.filter];
  const limit = options.limit ?? MAX_REVIEW_PER_SESSION;

  const due = await dueItems(kinds, limit);
  const dueRefs = new Set(due.map((item) => item.ref));
  const fresh = kinds.includes("word") ? await newWords(NEW_WORDS_PER_SESSION) : [];
  const reinforce = kinds.includes("word") ? await reinforcementItems(dueRefs) : [];

  const wordRefs = [...due, ...reinforce].filter((item) => item.kind === "word");
  const words = await wordsById(wordRefs.map((item) => Number(item.ref.slice(5))));
  for (const word of fresh) words.set(word.id, word);
  const sentences = await sentencesFor([...words.values()]);
  const sessionWords = [...words.values()].map((word) => word.spanish);

  const phrases = await phraseCards(due.filter((item) => item.kind === "phrase"));
  const games = await gameCards(due.filter((item) => item.kind === "game_item"));

  let wordIndex = 0;
  const viewFor = (): "cloze" | "scramble" =>
    options.mode === "mixed" ? (wordIndex++ % 2 === 0 ? "cloze" : "scramble") : options.mode;

  const toWordCard = (item: { ref: string; source: string; box: number; isNew: boolean }) => {
    const word = words.get(Number(item.ref.slice(5)));
    const sentence = word && sentences.get(word.id);
    return word && sentence ? wordCard(item, word, sentence, viewFor(), sessionWords) : null;
  };

  const dueCards = await Promise.all(
    due.map(async (item): Promise<SessionCard | null> => {
      switch (item.kind) {
        case "word":
          return toWordCard({ ...item, isNew: false });
        case "phrase":
          return phrases.get(item.ref) ?? null;
        case "game_item":
          return games.get(item.ref) ?? null;
        case "conjugation": {
          const combo = parseConjRef(item.ref);
          return combo
            ? conjugationCard(combo, { source: item.source, box: item.box, isNew: false }, true)
            : null;
        }
      }
    }),
  );

  const newCards = fresh.map((word) =>
    toWordCard({ ref: `word:${word.id}`, source: "spanyard", box: 0, isNew: true }),
  );
  const extraCards = reinforce.map((item) => toWordCard({ ...item, isNew: false }));

  const present = (cards: (SessionCard | null)[]) =>
    cards.filter((card): card is SessionCard => card !== null);
  return interleave([...present(dueCards), ...present(newCards)], present(extraCards));
}

/**
 * The Conjugar drill: due forms in the chosen tense group first, topped up with
 * fresh combos (irregulars weighted double), each with a Claude sentence.
 */
export async function buildConjugationDrill(group: TenseGroup, count = 10): Promise<SessionCard[]> {
  const tenses = TENSE_GROUPS[group];
  const due = (await dueItems(["conjugation"], 50))
    .map((item) => ({ item, combo: parseConjRef(item.ref) }))
    .filter(({ combo }) => combo && (tenses as readonly string[]).includes(combo.tense))
    .slice(0, count);

  const fresh = pickCombos(
    count - due.length,
    tenses,
    new Set(due.map(({ item }) => item.ref)),
  );

  return Promise.all([
    ...due.map(({ item, combo }) =>
      conjugationCard(combo!, { source: item.source, box: item.box, isNew: false }, true),
    ),
    ...fresh.map((combo) => conjugationCard(combo, { source: "conjugar", box: 0, isNew: true }, true)),
  ]);
}

// ── stats ────────────────────────────────────────────────────────────────────

export async function reviewStats(): Promise<ReviewStats> {
  const user = currentUserId();
  const now = new Date().toISOString();

  const [items, { count: totalWords, error: wordsError }] = await Promise.all([
    fetchAll<{ kind: ReviewKind; box: number; next_review_at: string }>((from, to) =>
      db()
        .from("srs_items")
        .select("kind, box, next_review_at")
        .eq("user_id", user)
        .eq("suspended", false)
        .order("id")
        .range(from, to),
    ),
    db().from("words").select("id", { count: "exact", head: true }),
  ]);
  if (wordsError) throw new Error(wordsError.message);

  const dueByKind: Record<ReviewKind, number> = { word: 0, phrase: 0, conjugation: 0, game_item: 0 };
  const wordBoxes = [0, 0, 0, 0, 0, 0];
  let seenWords = 0;
  for (const item of items) {
    if (new Date(item.next_review_at).toISOString() <= now) dueByKind[item.kind]++;
    if (item.kind === "word") {
      wordBoxes[item.box]++;
      seenWords++;
    }
  }
  const total = totalWords ?? 0;
  wordBoxes[0] = Math.max(total - seenWords, 0);

  return {
    dueByKind,
    due: Object.values(dueByKind).reduce((a, b) => a + b, 0),
    newWords: Math.min(NEW_WORDS_PER_SESSION, wordBoxes[0]),
    wordBoxes,
    fluency: fluencyScore(wordBoxes, Math.max(total, 1)),
  };
}
