/**
 * Parser fixtures: [scene, answer, expected].
 *   "detras_de:seto"               one phrase, expression:ref ids
 *   "entre:seto,jarron"            two references
 *   "al_lado_de:arbol+cerca_de:seto" two phrases
 *   "boca_abajo:"                  no reference
 *   "!de-el"                       grammar block with that rule
 *   "?"                            not parsed (goes to the Claude fallback)
 * Ambiguous nouns list every candidate id: "lapida_grande|lapida_pequena|lapida_rota".
 */
export const FIXTURES: [string, string, string][] = [
  // ── subject + verb + expression + reference, accents on and off
  ["jardin", "El gnomo está detrás del seto.", "detras_de:seto"],
  ["jardin", "el gnomo esta detras del seto", "detras_de:seto"],
  ["jardin", "EL GNOMO ESTÁ DETRÁS DEL SETO", "detras_de:seto"],
  ["jardin", "El gnomo está detrás del arbusto.", "detras_de:seto"],
  ["jardin", "el gnomo esta detras del matorral", "detras_de:seto"],
  ["jardin", "El duende está detrás del seto.", "detras_de:seto"],
  ["jardin", "el enano esta detras del seto", "detras_de:seto"],
  ["jardin", "El gnomito está detrás del seto", "detras_de:seto"],
  ["jardin", "¿El gnomo? Está detrás del seto.", "detras_de:seto"],
  ["jardin", "Él está detrás del seto.", "detras_de:seto"],
  ["jardin", "el esta detras del seto", "detras_de:seto"],
  ["jardin", "El gnomo está dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "el gnomo esta dentro del jarron", "dentro_de:jarron"],
  ["jardin", "esta dentro de la maceta", "dentro_de:jarron"],
  ["jardin", "está dentro del tiesto", "dentro_de:jarron"],
  ["jardin", "El gnomo está en el jarrón.", "en:jarron"],
  ["jardin", "esta en la maceta", "en:jarron"],
  ["jardin", "El gnomo está debajo del banco.", "debajo_de:banco"],
  ["jardin", "esta debajo del banco", "debajo_de:banco"],
  ["jardin", "El gnomo está bajo el banco.", "bajo:banco"],
  ["jardin", "está por debajo del banco", "por_debajo_de:banco"],
  ["jardin", "El gnomo está encima de la estatua.", "encima_de:estatua"],
  ["jardin", "esta encima de la estatua", "encima_de:estatua"],
  ["jardin", "está sobre la estatua", "sobre:estatua"],
  ["jardin", "está en lo alto de la estatua", "en_lo_alto_de:estatua"],
  ["jardin", "esta en lo alto de la estatua", "en_lo_alto_de:estatua"],
  ["jardin", "El gnomo está al lado del árbol.", "al_lado_de:arbol"],
  ["jardin", "esta al lado del arbol", "al_lado_de:arbol"],
  ["jardin", "está junto al árbol", "junto_a:arbol"],
  ["jardin", "esta junto al arbol", "junto_a:arbol"],
  ["jardin", "está cerca del árbol", "cerca_de:arbol"],
  ["jardin", "esta cerca de las flores", "cerca_de:flores"],
  ["jardin", "está cerca del parterre", "cerca_de:flores"],
  ["jardin", "está cerca del macizo de flores", "cerca_de:flores"],
  ["jardin", "está lejos de la verja", "lejos_de:verja"],
  ["jardin", "esta lejos de la puerta", "lejos_de:verja"],
  ["jardin", "está fuera del jardín", "fuera_de:jardin"],
  ["jardin", "esta fuera del jardin", "fuera_de:jardin"],
  ["jardin", "está afuera del jardín", "afuera_de:jardin"],
  ["jardin", "está en el exterior del jardín", "en_el_exterior_de:jardin"],
  ["jardin", "está a la derecha de la estatua", "a_la_derecha_de:estatua"],
  ["jardin", "esta a la izquierda del arbol", "a_la_izquierda_de:arbol"],
  ["jardin", "está delante del seto", "delante_de:seto"],
  ["jardin", "esta delante del banco", "delante_de:banco"],
  ["jardin", "está enfrente de la estatua", "enfrente_de:estatua"],
  ["jardin", "esta en frente de la estatua", "enfrente_de:estatua"],
  ["jardin", "está frente a la estatua", "frente_a:estatua"],
  ["jardin", "está frente al banco", "frente_a:banco"],
  ["jardin", "está colgado del árbol", "colgado_de:arbol"],
  ["jardin", "esta colgado del arbol", "colgado_de:arbol"],
  ["jardin", "está colgado en el árbol", "colgado_de:arbol"],
  ["jardin", "está en el árbol", "en:arbol"],
  ["jardin", "está en la parte de arriba del árbol", "en_la_parte_de_arriba_de:arbol"],
  ["jardin", "está en la parte superior del árbol", "en_la_parte_de_arriba_de:arbol"],
  ["jardin", "esta en la parte de abajo del arbol", "en_la_parte_de_abajo_de:arbol"],
  ["jardin", "está en el cofre", "en:cofre"],
  ["jardin", "está dentro del baúl", "dentro_de:cofre"],
  ["jardin", "está junto a la verja", "junto_a:verja"],
  ["jardin", "está al otro lado de la verja", "al_otro_lado_de:verja"],
  ["jardin", "esta del otro lado de la cancela", "al_otro_lado_de:verja"],
  ["jardin", "está en el rincón del jardín", "en_el_rincon_de:jardin"],
  ["jardin", "esta en el rincon del jardin", "en_el_rincon_de:jardin"],
  ["jardin", "está en la esquina del jardín", "en_la_esquina_de:jardin"],
  ["jardin", "está al fondo del jardín", "al_fondo_de:jardin"],
  ["jardin", "esta al fondo del jardin", "al_fondo_de:jardin"],
  ["jardin", "está en medio del jardín", "en_medio_de:jardin"],
  ["jardin", "está en el centro del jardín", "en_el_centro_de:jardin"],
  ["jardin", "está entre las flores", "entre:flores"],
  ["jardin", "está en las flores", "en:flores"],
  ["jardin", "está al pie del árbol", "al_pie_de:arbol"],
  ["jardin", "está al pie de la estatua", "al_pie_de:estatua"],
  ["jardin", "está tras el seto", "tras:seto"],
  ["jardin", "está por detrás del seto", "por_detras_de:seto"],
  ["jardin", "está por delante del banco", "por_delante_de:banco"],
  ["jardin", "está atrás del seto", "atras_de:seto"],
  ["jardin", "esta atras del seto", "atras_de:seto"],
  ["jardin", "está arriba de la estatua", "arriba_de:estatua"],
  ["jardin", "está abajo del banco", "abajo_de:banco"],
  ["jardin", "está adentro del jarrón", "adentro_de:jarron"],
  ["jardin", "esta adentro de la maceta", "adentro_de:jarron"],
  ["jardin", "está pegado al seto", "pegado_a:seto"],
  ["jardin", "esta pegado al seto", "pegado_a:seto"],
  ["jardin", "está apoyado en el banco", "apoyado_en:banco"],
  ["jardin", "está apoyado contra el banco", "apoyado_en:banco"],
  ["jardin", "está de cara a la estatua", "de_cara_a:estatua"],
  ["jardin", "está en diagonal al cofre", "en_diagonal_a:cofre"],
  ["jardin", "está más allá del banco", "mas_alla_de:banco"],
  ["jardin", "esta mas alla del banco", "mas_alla_de:banco"],
  ["jardin", "está por encima del banco", "por_encima_de:banco"],
  ["jardin", "está en el interior del jarrón", "en_el_interior_de:jarron"],
  ["jardin", "está al fondo del jarrón", "al_fondo_de:jarron"],
  ["jardin", "está en el borde del jarrón", "en_el_borde_de:jarron"],
  ["jardin", "está al borde del jarrón", "en_el_borde_de:jarron"],

  // ── entre … y … (and e)
  ["jardin", "El gnomo está entre el seto y el jarrón.", "entre:seto,jarron"],
  ["jardin", "esta entre el seto y el jarron", "entre:seto,jarron"],
  ["jardin", "está entre la maceta y el arbusto", "entre:jarron,seto"],
  ["jardin", "está entre el árbol y la estatua", "entre:arbol,estatua"],
  ["jardin", "entre el seto y el jarrón", "entre:seto,jarron"],
  ["jardin", "Está a medio camino entre el seto y el jarrón.", "a_medio_camino_entre:seto,jarron"],
  ["jardin", "esta a mitad de camino entre el seto y el jarron", "a_medio_camino_entre:seto,jarron"],
  ["cementerio", "está entre la lápida pequeña y la lápida rota", "entre:lapida_pequena,lapida_rota"],
  ["cementerio", "esta entre la lapida pequena y la lapida rota", "entre:lapida_pequena,lapida_rota"],
  ["cementerio", "está entre las lápidas", "entre:lapidas"],
  ["cementerio", "está entre las tumbas", "entre:lapidas"],
  ["cementerio", "está entre medias de las lápidas", "entre_medias_de:lapidas"],
  ["cementerio", "está en medio de las tumbas", "en_medio_de:lapidas"],
  ["laberinto", "está entre la colina y la torre", "entre:colina,torre"],
  ["laberinto", "está a medio camino entre la colina y la torre", "a_medio_camino_entre:colina,torre"],
  ["laberinto", "está entre el estanque y el camino", "entre:estanque,camino"],

  // ── subjectless and verbless answers
  ["jardin", "Detrás del seto.", "detras_de:seto"],
  ["jardin", "detras del seto", "detras_de:seto"],
  ["jardin", "Está detrás del seto.", "detras_de:seto"],
  ["jardin", "esta detras del seto", "detras_de:seto"],
  ["jardin", "Dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "debajo del banco", "debajo_de:banco"],
  ["jardin", "en el jarrón", "en:jarron"],
  ["jardin", "encima de la estatua", "encima_de:estatua"],
  ["jardin", "al lado del árbol", "al_lado_de:arbol"],
  ["jardin", "junto al seto", "junto_a:seto"],
  ["jardin", "Se encuentra detrás del seto.", "detras_de:seto"],
  ["jardin", "se encuentra detras del seto", "detras_de:seto"],
  ["jardin", "Queda detrás del seto.", "detras_de:seto"],
  ["jardin", "Se esconde detrás del seto.", "detras_de:seto"],
  ["jardin", "Se ha escondido dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "El gnomo se esconde detrás del seto.", "detras_de:seto"],
  ["jardin", "Está escondido detrás del seto.", "detras_de:seto"],
  ["jardin", "El gnomo está escondido dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "Está sentado encima de la estatua.", "encima_de:estatua"],
  ["jardin", "Está agachado debajo del banco.", "debajo_de:banco"],
  ["jardin", "Está metido en el jarrón.", "en:jarron"],

  // ── fillers and modifiers
  ["jardin", "Creo que está detrás del seto.", "detras_de:seto"],
  ["jardin", "creo que esta detras del seto", "detras_de:seto"],
  ["jardin", "Yo creo que el gnomo está detrás del seto.", "detras_de:seto"],
  ["jardin", "Pues está detrás del seto.", "detras_de:seto"],
  ["jardin", "Mira, está detrás del seto.", "detras_de:seto"],
  ["jardin", "Está justo detrás del seto.", "detras_de:seto"],
  ["jardin", "esta justo detras del seto", "detras_de:seto"],
  ["jardin", "Está muy cerca del árbol.", "cerca_de:arbol"],
  ["jardin", "Está bastante lejos de la verja.", "lejos_de:verja"],
  ["jardin", "Está un poco detrás del seto.", "detras_de:seto"],
  ["jardin", "Está casi al lado del árbol.", "al_lado_de:arbol"],
  ["jardin", "Ahora está detrás del seto.", "detras_de:seto"],
  ["jardin", "Está detrás del seto, creo.", "detras_de:seto"],
  ["jardin", "Sí, está detrás del seto.", "detras_de:seto"],
  ["jardin", "Vale, está dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "Bueno, el gnomo está debajo del banco.", "debajo_de:banco"],

  // ── inverted order and hay
  ["jardin", "Detrás del seto está el gnomo.", "detras_de:seto"],
  ["jardin", "detras del seto esta el gnomo", "detras_de:seto"],
  ["jardin", "Hay un gnomo detrás del seto.", "detras_de:seto"],
  ["jardin", "hay un gnomo detras del seto", "detras_de:seto"],
  ["jardin", "Detrás del seto hay un gnomo.", "detras_de:seto"],
  ["jardin", "Hay un duende dentro del jarrón.", "dentro_de:jarron"],
  ["jardin", "Está el gnomo detrás del seto.", "detras_de:seto"],

  // ── two phrases
  ["jardin", "Está al lado del árbol y cerca del seto.", "al_lado_de:arbol+cerca_de:seto"],
  ["jardin", "Está detrás del seto y cerca del árbol.", "detras_de:seto+cerca_de:arbol"],
  ["jardin", "Está boca abajo en el árbol.", "boca_abajo:+en:arbol"],
  ["jardin", "Está colgado del árbol, boca abajo.", "colgado_de:arbol+boca_abajo:"],
  ["jardin", "Está allí, detrás del seto.", "alli:+detras_de:seto"],

  // ── reference-less and bare forms
  ["jardin", "Está arriba.", "arriba:"],
  ["jardin", "esta arriba", "arriba:"],
  ["jardin", "Está abajo.", "abajo:"],
  ["jardin", "Está al revés.", "al_reves:"],
  ["jardin", "esta al reves", "al_reves:"],
  ["jardin", "Está boca abajo.", "boca_abajo:"],
  ["jardin", "Está boca arriba.", "boca_arriba:"],
  ["jardin", "Está aquí.", "aqui:"],
  ["jardin", "esta aqui", "aqui:"],
  ["jardin", "Está ahí.", "ahi:"],
  ["jardin", "Está allí.", "alli:"],
  ["jardin", "esta alli", "alli:"],
  ["jardin", "Está acá.", "aca:"],
  ["jardin", "Está allá.", "alla:"],
  ["jardin", "Está encima.", "encima_de:"],
  ["jardin", "Está debajo.", "debajo_de:"],
  ["jardin", "Está detrás.", "detras_de:"],
  ["jardin", "Está dentro.", "dentro_de:"],
  ["jardin", "Está fuera.", "fuera_de:"],
  ["jardin", "Está afuera.", "afuera_de:"],
  ["jardin", "Está al lado.", "al_lado_de:"],
  ["jardin", "Está cerca.", "cerca_de:"],
  ["jardin", "Está lejos.", "lejos_de:"],
  ["jardin", "Está a la derecha.", "a_la_derecha_de:"],
  ["jardin", "Está a la izquierda.", "a_la_izquierda_de:"],
  ["jardin", "Está al fondo.", "al_fondo_de:"],
  ["jardin", "Está en el centro.", "en_el_centro_de:"],
  ["jardin", "Está en medio.", "en_medio_de:"],
  ["jardin", "Está en el rincón.", "en_el_rincon_de:"],
  ["jardin", "Está en la esquina.", "en_la_esquina_de:"],
  ["jardin", "Está al otro lado.", "al_otro_lado_de:"],
  ["jardin", "Está a mano derecha.", "a_mano_derecha:"],
  ["jardin", "Está a mano izquierda.", "a_mano_izquierda:"],
  ["jardin", "Está todo recto.", "todo_recto:"],
  ["jardin", "Está todo derecho.", "todo_recto:"],
  ["jardin", "Está enfrente.", "enfrente_de:"],
  ["jardin", "Está más allá.", "mas_alla_de:"],
  ["jardin", "Está en lo alto.", "en_lo_alto_de:"],
  ["cementerio", "Está en el sótano.", "en_el_sotano:"],
  ["cementerio", "Está en el sótano del mausoleo.", "en_el_sotano:mausoleo"],
  ["cementerio", "esta en el sotano de la cripta", "en_el_sotano:mausoleo"],
  ["cementerio", "Está en el piso de abajo.", "abajo:"],
  ["laberinto", "Está en el piso de arriba.", "arriba:"],
  ["laberinto", "Está en la planta baja.", "en_la_planta_baja:"],
  ["laberinto", "Está en el primer piso.", "en_el_primer_piso:"],
  ["laberinto", "Está en la primera planta.", "en_el_primer_piso:"],
  ["mercado", "Está al final de la calle.", "al_final_de_la_calle:"],
  ["mercado", "Está a la vuelta de la esquina.", "a_la_vuelta_de_la_esquina:"],
  ["mercado", "Está en la acera de enfrente.", "en_la_acera_de_enfrente:"],
  ["mercado", "Está cruzando la calle.", "cruzando_la_calle:"],

  // ── distances
  ["jardin", "Está a un metro del árbol.", "a_distancia_de:arbol"],
  ["jardin", "esta a un metro del arbol", "a_distancia_de:arbol"],
  ["jardin", "Está a dos metros de la estatua.", "a_distancia_de:estatua"],
  ["jardin", "Está a 3 metros del cofre.", "a_distancia_de:cofre"],
  ["jardin", "Está a unos pasos del banco.", "a_distancia_de:banco"],
  ["jardin", "Está a pocos metros de la verja.", "a_distancia_de:verja"],
  ["jardin", "Está a dos pasos del seto.", "a_distancia_de:seto"],
  ["mercado", "Está a dos manzanas de la fuente.", "a_manzanas_de:fuente"],
  ["mercado", "Está a dos cuadras de la fuente.", "a_cuadras_de:fuente"],
  ["mercado", "Está a una cuadra del pozo.", "a_cuadras_de:pozo"],

  // ── mercado
  ["mercado", "El gnomo está dentro del pozo.", "dentro_de:pozo"],
  ["mercado", "esta en el pozo", "en:pozo"],
  ["mercado", "Está al fondo del pozo.", "al_fondo_de:pozo"],
  ["mercado", "Está enfrente del puesto de fruta.", "enfrente_de:puesto"],
  ["mercado", "esta enfrente del puesto de frutas", "enfrente_de:puesto"],
  ["mercado", "Está frente al puesto.", "frente_a:puesto"],
  ["mercado", "Está de cara al puesto.", "de_cara_a:puesto"],
  ["mercado", "Está debajo del puesto de fruta.", "debajo_de:puesto"],
  ["mercado", "Está en el centro de la plaza.", "en_el_centro_de:plaza"],
  ["mercado", "esta en el centro de la plaza", "en_el_centro_de:plaza"],
  ["mercado", "Está en medio de la plaza.", "en_medio_de:plaza"],
  ["mercado", "Está en medio del mercado.", "en_medio_de:plaza"],
  ["mercado", "Está alrededor de la fuente.", "alrededor_de:fuente"],
  ["mercado", "Da vueltas alrededor de la fuente.", "alrededor_de:fuente"],
  ["mercado", "El gnomo está dando vueltas alrededor de la fuente.", "alrededor_de:fuente"],
  ["mercado", "Corre en torno a la fuente.", "en_torno_a:fuente"],
  ["mercado", "Está entre la caja y el carro.", "entre:caja,carro"],
  ["mercado", "esta entre el cajon y la carreta", "entre:caja,carro"],
  ["mercado", "Está al lado del carrito.", "al_lado_de:carro"],
  ["mercado", "Está en la esquina de la calle Mayor con la calle del Pozo.", "en_la_esquina_con:calle_mayor,calle_pozo"],
  ["mercado", "esta en la esquina de la calle mayor con la calle del pozo", "en_la_esquina_con:calle_mayor,calle_pozo"],
  ["mercado", "Está en la esquina de la calle Mayor y la calle del Pozo.", "en_la_esquina_con:calle_mayor,calle_pozo"],
  ["mercado", "Está en la esquina de la calle Mayor.", "en_la_esquina_de:calle_mayor"],
  ["mercado", "Está al final de la calle Mayor.", "al_final_de:calle_mayor"],
  ["mercado", "Está al principio de la calle del Pozo.", "al_principio_de:calle_pozo"],
  ["mercado", "Está al comienzo de la calle del Pozo.", "al_principio_de:calle_pozo"],
  ["mercado", "Está colgado de la farola.", "colgado_de:farola"],
  ["mercado", "Está por encima del puesto.", "por_encima_de:puesto"],
  ["mercado", "Está en lo alto de la farola.", "en_lo_alto_de:farola"],
  ["mercado", "Está al pie de la farola.", "al_pie_de:farola"],
  ["mercado", "Está en el borde de la fuente.", "en_el_borde_de:fuente"],

  // ── cementerio
  ["cementerio", "Está apoyado en la lápida grande.", "apoyado_en:lapida_grande"],
  ["cementerio", "esta apoyado en la lapida grande", "apoyado_en:lapida_grande"],
  ["cementerio", "Está apoyado contra la tumba grande.", "apoyado_en:lapida_grande"],
  ["cementerio", "Está pegado a la lápida grande.", "pegado_a:lapida_grande"],
  ["cementerio", "Está delante de la lápida.", "delante_de:lapida_grande|lapida_pequena|lapida_rota"],
  ["cementerio", "Está al otro lado de la valla.", "al_otro_lado_de:valla"],
  ["cementerio", "esta al otro lado de la valla", "al_otro_lado_de:valla"],
  ["cementerio", "Está al otro lado de la reja.", "al_otro_lado_de:valla"],
  ["cementerio", "Está detrás de la valla.", "detras_de:valla"],
  ["cementerio", "Está al fondo del cementerio.", "al_fondo_de:cementerio"],
  ["cementerio", "Está en el rincón del cementerio.", "en_el_rincon_de:cementerio"],
  ["cementerio", "Está al pie del árbol seco.", "al_pie_de:arbol_seco"],
  ["cementerio", "esta al pie del arbol seco", "al_pie_de:arbol_seco"],
  ["cementerio", "Está al pie del árbol.", "al_pie_de:arbol_seco"],
  ["cementerio", "Está dentro del ataúd.", "dentro_de:ataud"],
  ["cementerio", "esta dentro del ataud", "dentro_de:ataud"],
  ["cementerio", "Está tumbado boca arriba dentro del ataúd.", "boca_arriba:+dentro_de:ataud"],
  ["cementerio", "Está dentro del mausoleo.", "dentro_de:mausoleo"],
  ["cementerio", "Está en la cripta.", "en:mausoleo"],
  ["cementerio", "Está dentro del panteón.", "dentro_de:mausoleo"],

  // ── laberinto
  ["laberinto", "Mira a través de la reja.", "a_traves_de:reja"],
  ["laberinto", "El gnomo mira a través de la reja.", "a_traves_de:reja"],
  ["laberinto", "esta a traves de la reja", "a_traves_de:reja"],
  ["laberinto", "Se asoma a través de la puerta.", "a_traves_de:reja"],
  ["laberinto", "Está en lo alto de la torre.", "en_lo_alto_de:torre"],
  ["laberinto", "esta en lo alto de la torre", "en_lo_alto_de:torre"],
  ["laberinto", "Está en la punta de la torre.", "en_la_punta_de:torre"],
  ["laberinto", "Está encima de la torre.", "encima_de:torre"],
  ["laberinto", "Está al pie de la torre.", "al_pie_de:torre"],
  ["laberinto", "Está sentado al pie de la torre.", "al_pie_de:torre"],
  ["laberinto", "Está en la cima de la colina.", "en_la_cima_de:colina"],
  ["laberinto", "esta en la cima de la colina", "en_la_cima_de:colina"],
  ["laberinto", "Está más allá de la reja.", "mas_alla_de:reja"],
  ["laberinto", "Está al otro lado del seto.", "al_otro_lado_de:seto_largo"],
  ["laberinto", "Está al otro lado del muro de setos.", "al_otro_lado_de:seto_largo"],
  ["laberinto", "Está a orillas del estanque.", "a_orillas_de:estanque"],
  ["laberinto", "esta a orillas del estanque", "a_orillas_de:estanque"],
  ["laberinto", "Está en la orilla del estanque.", "en_la_orilla_de:estanque"],
  ["laberinto", "Está al final del camino.", "al_final_de:camino"],
  ["laberinto", "esta al final del sendero", "al_final_de:camino"],
  ["laberinto", "Está a lo largo del camino.", "a_lo_largo_de:camino"],
  ["laberinto", "Está tumbado boca abajo en el camino.", "boca_abajo:+en:camino"],
  ["laberinto", "Está al fondo del pasillo.", "al_fondo_de:camino"],
  ["laberinto", "Está en el interior de la torre.", "en_el_interior_de:torre"],

  // ── agreement (participles agree with el gnomo)
  ["cementerio", "Está apoyada en la lápida grande.", "!participle-agreement"],
  ["cementerio", "Está apoyados en la lápida grande.", "!participle-agreement"],
  ["jardin", "Está pegada al seto.", "!participle-agreement"],
  ["jardin", "Está colgada del árbol.", "!participle-agreement"],
  ["jardin", "Está escondida detrás del seto.", "!participle-agreement"],
  ["jardin", "Está sentada encima de la estatua.", "!participle-agreement"],
  ["jardin", "El gnomo están detrás del seto.", "!estar-agreement"],
  ["jardin", "Están detrás del seto.", "!estar-agreement"],
  ["jardin", "Los gnomos están detrás del seto.", "!subject-number"],
  ["jardin", "La gnomo está detrás del seto.", "!article-gender"],

  // ── grammar traps
  ["jardin", "Hay el gnomo detrás del seto.", "!hay-definite"],
  ["jardin", "hay el gnomo detras del seto", "!hay-definite"],
  ["jardin", "Detrás del seto hay el gnomo.", "!hay-definite"],
  ["jardin", "Hay detrás del seto.", "!hay-subject"],
  ["jardin", "Un gnomo está detrás del seto.", "!estar-indefinite"],
  ["jardin", "Está un gnomo detrás del seto.", "!estar-indefinite"],
  ["jardin", "El gnomo está detrás de el seto.", "!de-el"],
  ["jardin", "esta detras de el seto", "!de-el"],
  ["jardin", "Está dentro de el jarrón.", "!de-el"],
  ["jardin", "Está al lado de el árbol.", "!de-el"],
  ["jardin", "Está junto a el árbol.", "!a-el"],
  ["jardin", "esta junto a el arbol", "!a-el"],
  ["mercado", "Está frente a el puesto.", "!a-el"],
  ["jardin", "Está detrás el seto.", "!missing-de"],
  ["jardin", "Está encima la estatua.", "!missing-de"],
  ["jardin", "Está dentro el jarrón.", "!missing-de"],
  ["jardin", "Está junto el árbol.", "!missing-de"],
  ["jardin", "Está cerca la verja.", "!missing-de"],
  ["jardin", "Está entre del seto y del jarrón.", "!extra-de"],
  ["jardin", "Está detrás de la seto.", "!article-gender"],
  ["jardin", "Está detrás del estatua.", "!article-gender"],
  ["jardin", "Está encima del estatua.", "!article-gender"],
  ["jardin", "Está dentro de la jarrón.", "!article-gender"],
  ["jardin", "Está debajo de la banco.", "!article-gender"],
  ["jardin", "Está cerca de los flores.", "!article-gender"],
  ["jardin", "Está cerca del flores.", "!article-gender"],
  ["mercado", "Está en el fuente.", "!article-gender"],
  ["jardin", "El gnomo es detrás del seto.", "!ser-location"],
  ["jardin", "Es detrás del seto.", "!ser-location"],
  ["jardin", "Está entre el seto.", "!entre-two"],

  // ── not parsed (Claude fallback)
  ["jardin", "", "?"],
  ["jardin", "no sé", "?"],
  ["jardin", "hola", "?"],
  ["jardin", "está detrás de la nevera", "?"],
  ["jardin", "está en el coche", "?"],
  ["jardin", "está detrás del seto grande azul enorme", "?"],
  ["jardin", "el perro está detrás del seto", "?"],
];
