/**
 * src/content/verbs.json → supabase/seed/verbs.sql (upserts todo.verbs).
 * The app reads the bundled JSON; the table mirrors it for SQL access.
 */
import { writeFileSync } from "node:fs";
import verbs from "../src/content/verbs.json";

const q = (value: string) => `'${value.replace(/'/g, "''")}'`;

const rows = verbs.map(
  (verb) =>
    `  (${q(verb.infinitive)}, ${q(verb.english)}, ${verb.isIrregular}, ${q(JSON.stringify(verb.forms))}::jsonb)`,
);

const sql = `-- GENERATED by scripts/seed-sql.ts from src/content/verbs.json. Do not edit by hand.
insert into todo.verbs (infinitive, english, is_irregular, forms) values
${rows.join(",\n")}
on conflict (infinitive) do update set
  english = excluded.english,
  is_irregular = excluded.is_irregular,
  forms = excluded.forms;
`;

writeFileSync(new URL("../supabase/seed/verbs.sql", import.meta.url), sql);
console.log(`verbs.sql: ${verbs.length} verbs`);
